name: Suhas - CD to staging

on: 
 push:
  branches: 
   - 'suhas/**'
 #pull_request:
 # paths:
 #  - 'apis/poi/**'


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        
    - name: Start Staging
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |                
          az webapp start --name openhacktdp1i383poi --resource-group openhacktdp1i383rg --slot staging
    
    - name: Setup Docker and ACR environment
      uses: azure/docker-login@v1
      with:
        login-server: openhacktdp1i383acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}  
     
    - name: Build and Push Docker Image
      run: |
        docker build ./apis/poi/web -t openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}     
    - name: Deploy to App Service using the ACR image
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhacktdp1i383poi'
        publish-profile: ${{ secrets.AZURE_POIAPP_PUBLISH_PROFILE_STAGING }}
        images: 'openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'
        slot-name: staging

    - name: Check if the staging slot is healthy using cURL      
      run: |         
       code=true
       for i in {1..10}       
          do
            response=$(curl -m 5 -s -w "%{http_code}" "https://openhacktdp1i383poi-staging.azurewebsites.net/api/healthcheck/poi")
            http_code=$(tail -n1 <<< "$response") 
            echo "Status:" "$http_code" 
             if [ "$http_code" == "}200" ] 
             then
              break
             else
               code=false
             fi
             sleep 30
          done
       echo "$code"
       if [ "$code" == false ] 
       then
        exit 1
       fi      
    
    - name: Performing Slot Swap and Stop Staging Slot
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |          
          az webapp deployment slot swap  -g openhacktdp1i383rg -n openhacktdp1i383poi --slot staging \--target-slot production
          az webapp stop --name openhacktdp1i383poi --resource-group openhacktdp1i383rg --slot staging


   

