name: Suhas - CD to staging

on: 
 push:
  branches: 
   - 'suhas/**'
 #pull_request:
 # paths:
 #  - 'apis/poi/**'


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    
    - name: Setup Docker and ACR environment
      uses: azure/docker-login@v1
      with:
        login-server: openhacktdp1i383acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}  
     
    - name: Build and Push Docker Image
      run: |
        docker build ./apis/poi/web -t openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}     
    - name: Deploy to App Service using the ACR image
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhacktdp1i383poi'
        publish-profile: ${{ secrets.AZURE_POIAPP_PUBLISH_PROFILE_STAGING }}
        images: 'openhacktdp1i383acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}'
        slot-name: staging

    - name: Check if the staging slot is healthy using cURL
      run: |
         CODE=`curl --location --request GET 'http://openhacktdp1i383poi-staging.azurewebsites.net/api/healthcheck/poi'`
         if [ $CODE!="200" ] 
         then
         echo "FAILURE"
         else
         echo "SUCCESS"
         fi
