name: User-Java-Service - CI/CD

on: 
 push:
  branches: 
   - main
  paths: 
   - 'apis/user-java/**'
 #pull_request:
 # paths:
 #  - 'apis/user-java/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      working-directory: ./apis/user-java
      run: mvn -B package --file pom.xml

    - name: Unit Test
      working-directory: ./apis/user-java
      id: UnitTest
      run: mvn test
      continue-on-error: true
    
    - name: Create an Issue if the job fails    
      if: ${{ steps.UnitTest.outcome != 'success' }}
      uses: JasonEtco/create-an-issue@v2
      env:
         GITHUB_TOKEN: ${{ secrets.ADNAN_TOKEN}}
    
    - name: Exit On Failed Unit Test
      if: ${{ steps.UnitTest.outcome != 'success' }}
      run: exit 1

    - name: Setup Docker and ACR environment
      uses: azure/docker-login@v1
      with:
        login-server: openhacktdp1i383acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build ./apis/user-java -t openhacktdp1i383acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}
        docker push openhacktdp1i383acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}     

    - name: Deploy to App Service using the ACR image
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhacktdp1i383userjava'
        publish-profile: ${{ secrets.AZURE_USERJAVAAPP_PUBLISH_PROFILE }}
        images: 'openhacktdp1i383acr.azurecr.io/devopsoh/api-user-java:${{ github.sha }}'
